import * as React from "react";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Autocomplete from "@mui/material/Autocomplete";

export default function LanguageSelect({ value, onChange }) {
  const languages = [
    { label: "Abkhazian" },
    { label: "Afar" },
    { label: "Afrikaans" },
    { label: "Akan" },
    { label: "Albanian" },
    { label: "Amharic" },
    { label: "Arabic" },
    { label: "Aragonese" },
    { label: "Armenian" },
    { label: "Assamese" },
    { label: "Avaric" },
    { label: "Avestan" },
    { label: "Aymara" },
    { label: "Azerbaijani" },
    { label: "Bambara" },
    { label: "Bashkir" },
    { label: "Basque" },
    { label: "Belarusian" },
    { label: "Bengali" },
    { label: "Bihari" },
    { label: "Bislama" },
    { label: "Bosnian" },
    { label: "Breton" },
    { label: "Bulgarian" },
    { label: "Burmese" },
    { label: "Catalan" },
    { label: "Chamorro" },
    { label: "Chechen" },
    { label: "Chichewa" },
    { label: "Chinese" },
    { label: "Chuvash" },
    { label: "Cornish" },
    { label: "Corsican" },
    { label: "Cree" },
    { label: "Croatian" },
    { label: "Czech" },
    { label: "Danish" },
    { label: "Divehi" },
    { label: "Dutch" },
    { label: "Dzongkha" },
    { label: "English" },
    { label: "Esperanto" },
    { label: "Estonian" },
    { label: "Ewe" },
    { label: "Faroese" },
    { label: "Fijian" },
    { label: "Finnish" },
    { label: "French" },
    { label: "Frisian" },
    { label: "Galician" },
    { label: "Georgian" },
    { label: "German" },
    { label: "Greek" },
    { label: "Greenlandic" },
    { label: "Guarani" },
    { label: "Gujarati" },
    { label: "Haitian Creole" },
    { label: "Hausa" },
    { label: "Hebrew" },
    { label: "Herero" },
    { label: "Hindi" },
    { label: "Hiri Motu" },
    { label: "Hungarian" },
    { label: "Icelandic" },
    { label: "Ido" },
    { label: "Igbo" },
    { label: "Indonesian" },
    { label: "Interlingua" },
    { label: "Interlingue" },
    { label: "Inuktitut" },
    { label: "Inupiak" },
    { label: "Irish" },
    { label: "Italian" },
    { label: "Japanese" },
    { label: "Javanese" },
    { label: "Kannada" },
    { label: "Kanuri" },
    { label: "Kashmiri" },
    { label: "Kazakh" },
    { label: "Khmer" },
    { label: "Kikuyu" },
    { label: "Kinyarwanda" },
    { label: "Kirghiz" },
    { label: "Kirundi" },
    { label: "Komi" },
    { label: "Kongo" },
    { label: "Korean" },
    { label: "Kurdish" },
    { label: "Kwanyama" },
    { label: "Lao" },
    { label: "Latin" },
    { label: "Latvian" },
    { label: "Limburgish" },
    { label: "Lingala" },
    { label: "Lithuanian" },
    { label: "Luba-Katanga" },
    { label: "Luxembourgish" },
    { label: "Macedonian" },
    { label: "Malagasy" },
    { label: "Malay" },
    { label: "Malayalam" },
    { label: "Maltese" },
    { label: "Manx" },
    { label: "Maori" },
    { label: "Marathi" },
    { label: "Marshallese" },
    { label: "Mongolian" },
    { label: "Nauru" },
    { label: "Navajo" },
    { label: "Ndonga" },
    { label: "Nepali" },
    { label: "Northern Sami" },
    { label: "Norwegian" },
    { label: "Occitan" },
    { label: "Ojibwa" },
    { label: "Oriya" },
    { label: "Oromo" },
    { label: "Ossetian" },
    { label: "Pali" },
    { label: "Panjabi" },
    { label: "Pashto" },
    { label: "Persian" },
    { label: "Polish" },
    { label: "Portuguese" },
    { label: "Quechua" },
    { label: "Romanian" },
    { label: "Romansh" },
    { label: "Rundi" },
    { label: "Russian" },
    { label: "Samoan" },
    { label: "Sango" },
    { label: "Sanskrit" },
    { label: "Sardinian" },
    { label: "Serbian" },
    { label: "Shona" },
    { label: "Sichuan Yi" },
    { label: "Sindhi" },
    { label: "Sinhalese" },
    { label: "Slovak" },
    { label: "Slovenian" },
    { label: "Somali" },
    { label: "Sotho" },
    { label: "Spanish" },
    { label: "Sundanese" },
    { label: "Swahili" },
    { label: "Swati" },
    { label: "Swedish" },
    { label: "Tagalog" },
    { label: "Tahitian" },
    { label: "Tajik" },
    { label: "Tamil" },
    { label: "Tatar" },
    { label: "Telugu" },
    { label: "Thai" },
    { label: "Tibetan" },
    { label: "Tigrinya" },
    { label: "Tonga" },
    { label: "Tsonga" },
    { label: "Tswana" },
    { label: "Turkish" },
    { label: "Turkmen" },
    { label: "Twi" },
    { label: "Uighur" },
    { label: "Ukrainian" },
    { label: "Urdu" },
    { label: "Uzbek" },
    { label: "Venda" },
    { label: "Vietnamese" },
    { label: "Volapük" },
    { label: "Walloon" },
    { label: "Welsh" },
    { label: "Western Frisian" },
    { label: "Wolof" },
    { label: "Xhosa" },
    { label: "Yiddish" },
    { label: "Yoruba" },
    { label: "Zhuang" },
    { label: "Zulu" },
  ];

  return (
    <Autocomplete
      id="language-select-demo"
      sx={{ width: 247 }}
      options={languages}
      value={value}
      onChange={(event, newValue) => {
        onChange({ name: "preferredLanguage", value: newValue });
      }}
      autoHighlight
      getOptionLabel={(option) => option.label}
      renderOption={(props, option) => (
        <Box component="li" {...props}>
          <img loading="lazy" width="20" alt="" />
          {option.label}
        </Box>
      )}
      renderInput={(params) => (
        <TextField
          {...params}
          label="Preferred Language"
          inputProps={{
            ...params.inputProps,
            autoComplete: "new-password",
          }}
        />
      )}
    />
  );
}
